name: Install Nginx on Self-hosted Runner

on:
  push:
    branches:
      - main

jobs:
  install-nginx:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Nginx
        run: |
          # Use curl to download the install script and execute it
          curl -O https://raw.githubusercontent.com/your-username/your-repo/main/path/to/install_nginx.sh
          chmod +x install_nginx.sh
          ./install_nginx.sh
